# Generated by Django 5.2.7 on 2025-11-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract", "0001_initial"),
        ("formal_sector", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="formal_sector",
            field=models.ForeignKey(
                help_text="Formal sector associated with the contract",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="formal_sector.formalsector",
            ),
        ),
        migrations.AddField(
            model_name="contractdetail",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="contract.contract",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="formal_sector",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Formal sector associated with the contract",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="formal_sector.formalsector",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
