# Generated by Django 5.2.7 on 2025-11-22 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formal_sector", "0002_initial"),
        ("insurance_coverage", "0004_remove_coverage_legacy_id"),
        ("insuree", "0001_initial"),
        ("organization", "0001_initial"),
        ("premium", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "policy_number",
                    models.CharField(
                        help_text="Unique policy identifier.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("draft", "Draft"),
                            ("entered-in-error", "Entered in Error"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "coverage",
                    models.ManyToManyField(
                        help_text="Coverages provided under this policy.",
                        to="insurance_coverage.coverage",
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        help_text="The insurance organization issuing the policy.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_policies",
                        to="organization.organization",
                    ),
                ),
                (
                    "policyholder",
                    models.ForeignKey(
                        help_text="Policyholder (organization or group purchasing the policy).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="formal_sector.formalsector",
                    ),
                ),
                (
                    "premium",
                    models.ForeignKey(
                        blank=True,
                        help_text="Premium payment terms linked to this policy.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="premium.premium",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        help_text="Primary insured person (if applicable).",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insuree.insuree",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Policies",
            },
        ),
    ]
