# Generated by Django 5.2.4 on 2025-08-09 17:20

import datetime
import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contribution_plan', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('stage', models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Renewed'), ('C', 'Cancelled'), ('E', 'Expired'), ('S', 'Suspended'), ('T', 'Terminated'), ('X', 'Closed')], max_length=1, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Idle'), (2, 'Active'), (4, 'Suspended'), (8, 'Expired'), (16, 'Ready')], null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('policy_holder_id', models.TextField()),
                ('enroll_date', models.DateField()),
                ('start_date', models.DateField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('offline', models.BooleanField(blank=True, null=True)),
                ('audit_user_id', models.IntegerField()),
                ('creation_date', models.DateField(auto_now=True, null=True)),
                ('updation_date', models.DateField(auto_now_add=True, null=True)),
                ('contribution_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.contributionplan')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('policy_holder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'db_table': 'tblPolicies',
                'managed': True,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
