# Generated by Django 5.2.4 on 2025-08-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insuree', '0007_delete_insureepermission'),
        ('policy', '0001_initial'),
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='premium',
            field=models.ForeignKey(blank=True, help_text='Premium payment terms linked to this policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premium'),
        ),
        migrations.AddField(
            model_name='policy',
            name='subscriber',
            field=models.ForeignKey(help_text='Primary insured person (if applicable).', on_delete=django.db.models.deletion.CASCADE, to='insuree.insuree'),
        ),
    ]
