# Generated by Django 5.2.4 on 2025-08-11 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contribution_plan', '0002_alter_contributionplan_allows_partial_payment_and_more'),
        ('insurance_coverage', '0002_initial'),
        ('insurance_plan', '0002_remove_insuranceplan_creation_date_and_more'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Optional reference code', max_length=64, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payer_object_id', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='NGN', help_text='ISO 4217 currency code', max_length=3)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField(help_text='When this premium installment is due')),
                ('period_start', models.DateField(blank=True, help_text='Coverage start date for this premium period', null=True)),
                ('period_end', models.DateField(blank=True, help_text='Coverage end date for this premium period', null=True)),
                ('frequency', models.CharField(blank=True, help_text='e.g. M (monthly), A (annual) or free text', max_length=10, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('due', 'Due'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='due', max_length=20)),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Days allowed after due_date before overdue')),
                ('invoice_reference', models.CharField(blank=True, help_text='Invoice or billing reference', max_length=128, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='External payment gateway reference', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_plan', models.ForeignKey(blank=True, help_text='Optional contribution plan that defines splitting / calculation rules', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='contribution_plan.contributionplan')),
                ('coverage', models.ForeignKey(blank=True, help_text='The specific coverage/policy instance this premium is for (preferred)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premiums', to='insurance_coverage.coverage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_premiums', to=settings.AUTH_USER_MODEL)),
                ('insurance_plan', models.ForeignKey(blank=True, help_text='The plan this premium is associated with (product level)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premiums', to='insurance_plan.insuranceplan')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_premiums', to='organization.organization')),
                ('payer_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'tblPremiums',
                'indexes': [models.Index(fields=['insurance_plan'], name='idx_premium_plan'), models.Index(fields=['coverage'], name='idx_premium_coverage'), models.Index(fields=['due_date'], name='idx_premium_due_date'), models.Index(fields=['status'], name='idx_premium_status')],
            },
        ),
    ]
