# Generated by Django 5.2.4 on 2025-08-09 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('insurance_period', models.PositiveIntegerField(help_text='Insurance period in months')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'tblProducts',
                'ordering': ['-created_at'],
            },
        ),
    ]
