# Generated by Django 5.2.1 on 2025-05-09 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Deleted'), (4, 'Restored'), (5, 'Archived'), (6, 'Unarchived'), (7, 'Imported'), (8, 'Exported'), (9, 'Synced'), (10, 'Merged'), (11, 'Split'), (12, 'Approved'), (13, 'Rejected'), (14, 'Cancelled'), (15, 'Completed'), (16, 'Failed'), (17, 'Started'), (18, 'Paused'), (19, 'Resumed'), (20, 'Stopped'), (21, 'Restarted'), (22, 'Scheduled'), (23, 'Unschedule'), (24, 'Locked'), (25, 'Unlocked'), (26, 'Verified'), (27, 'Unverified'), (28, 'Confirmed'), (29, 'Unconfirmed'), (30, 'Published'), (31, 'Unpublished'), (32, 'Drafted'), (33, 'Undrafted')], max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('request_header', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('api_type', models.CharField(choices=[(1, 'Graphql'), (2, 'Rest'), (3, 'Web')], default=2, max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'db_table': 'tblChangeLogs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
