# Generated by Django 5.2.1 on 2025-05-13 12:56

import datetime
import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.SmallIntegerField(db_column='EducationId', primary_key=True, serialize=False)),
                ('education', models.CharField(db_column='Education', max_length=50)),
            ],
            options={
                'db_table': 'tblEducations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FamilyType',
            fields=[
                ('code', models.CharField(db_column='FamilyTypeCode', max_length=2, primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='FamilyType', max_length=50)),
            ],
            options={
                'db_table': 'tblFamilyTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=1, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblGenders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('code', models.CharField(db_column='IdentificationCode', max_length=1, primary_key=True, serialize=False)),
                ('identification_type', models.CharField(db_column='IdentificationTypes', max_length=50)),
            ],
            options={
                'db_table': 'tblIdentificationTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.SmallIntegerField(db_column='ProfessionId', primary_key=True, serialize=False)),
                ('profession', models.CharField(db_column='Profession', max_length=50)),
            ],
            options={
                'db_table': 'tblProfessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.SmallIntegerField(db_column='RelationId', primary_key=True, serialize=False)),
                ('relation', models.CharField(db_column='Relation', max_length=50)),
            ],
            options={
                'db_table': 'tblRelations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='FamilyID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='FamilyUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('poverty', models.BooleanField(blank=True, db_column='Poverty', null=True)),
                ('address', models.CharField(blank=True, db_column='FamilyAddress', max_length=200, null=True)),
                ('is_offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('ethnicity', models.CharField(blank=True, db_column='Ethnicity', max_length=1, null=True)),
                ('confirmation_no', models.CharField(blank=True, db_column='ConfirmationNo', max_length=12, null=True)),
                ('audit_user', models.ForeignKey(db_column='AuditUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
                ('family_type', models.ForeignKey(blank=True, db_column='FamilyType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='families', to='insuree.familytype')),
            ],
            options={
                'db_table': 'tblFamilies',
                'managed': True,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Insuree',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='InsureeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='InsureeUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=50, null=True)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('other_names', models.CharField(db_column='OtherNames', max_length=100)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('head', models.BooleanField(db_column='IsHead', default=False)),
                ('marital', models.CharField(blank=True, db_column='Marital', max_length=1, null=True)),
                ('passport', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, db_column='CurrentAddress', max_length=200, null=True)),
                ('geolocation', models.CharField(blank=True, db_column='GeoLocation', max_length=250, null=True)),
                ('photo', models.FileField(blank=True, db_column='Photo', max_length=255, null=True, upload_to='insuree/photos/')),
                ('photo_date', models.DateField(blank=True, db_column='PhotoDate', null=True)),
                ('card_issued', models.BooleanField(blank=True, db_column='CardIssued', null=True)),
                ('offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('status', models.CharField(blank=True, choices=[('AC', 'Active'), ('IN', 'Inactive'), ('DE', 'Dead')], default='AC', max_length=2, null=True)),
                ('status_date', models.DateField(blank=True, db_column='StatusDate', null=True)),
                ('audit_user', models.ForeignKey(db_column='AuditUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('current_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.education')),
                ('family', models.ForeignKey(blank=True, db_column='FamilyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insuree.family')),
                ('gender', models.ForeignKey(blank=True, db_column='Gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.gender')),
                ('health_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.healthfacility')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.identificationtype')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.profession')),
                ('relationship', models.ForeignKey(blank=True, db_column='Relationship', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.relation')),
            ],
            options={
                'db_table': 'tblInsurees',
                'managed': True,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='family',
            name='head_insuree',
            field=models.ForeignKey(db_column='InsureeID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_of', to='insuree.insuree'),
        ),
    ]
