# Generated by Django 5.2.4 on 2025-08-09 17:20

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('insuree', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='insuree',
            name='chk_insuree_dob_not_future',
        ),
        migrations.AddConstraint(
            model_name='insuree',
            constraint=models.CheckConstraint(condition=models.Q(('dob__lte', datetime.date(2025, 8, 9))), name='chk_insuree_dob_not_future'),
        ),
    ]
