# Generated by Django 5.2.4 on 2025-08-10 14:08

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0002_remove_insuree_chk_insuree_dob_not_future_and_more'),
        ('location', '0002_rename_created_at_healthfacility_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificationtype',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Identification Type', 'verbose_name_plural': 'Identification Types'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'managed': True, 'ordering': ['profession'], 'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.RemoveConstraint(
            model_name='insuree',
            name='chk_insuree_dob_not_future',
        ),
        migrations.RemoveField(
            model_name='identificationtype',
            name='identification_type',
        ),
        migrations.RemoveField(
            model_name='identificationtype',
            name='requires_validation',
        ),
        migrations.RemoveField(
            model_name='identificationtype',
            name='validation_regex',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='familymembership',
            name='has_claim_benefits',
            field=models.BooleanField(default=False, help_text='Whether this membership has claim benefits'),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Whether this membership is valid'),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='name',
            field=models.CharField(blank=True, help_text='Identification type name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='prefix',
            field=models.CharField(blank=True, help_text='Prefix for the identification code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='regex',
            field=models.TextField(blank=True, help_text='Regular expression for validation', null=True),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='suffix',
            field=models.CharField(blank=True, help_text='Suffix for the identification code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='other_health_facility',
            field=models.ManyToManyField(blank=True, help_text='Other associated health facility', related_name='insurees_other_health_facility', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='secondary_health_facility',
            field=models.ForeignKey(blank=True, help_text='Secondary associated health facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurees_secondary_health_facility', to='location.healthfacility'),
        ),
        migrations.AlterField(
            model_name='identificationtype',
            name='code',
            field=models.CharField(help_text='Identification type code', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='chf_id',
            field=models.CharField(blank=True, help_text='CHF identification number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='Gender', null=True, on_delete=django.db.models.deletion.PROTECT, to='insuree.gender'),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='last_name',
            field=models.CharField(help_text='Last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='marital',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], help_text='Marital status', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='other_names',
            field=models.CharField(help_text='Other names', max_length=100),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the insuree', unique=True),
        ),
    ]
