# Generated by Django 5.2.4 on 2025-08-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0003_alter_identificationtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'managed': True, 'ordering': ['education'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education Levels'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'managed': True, 'ordering': ['relation'], 'verbose_name': 'Relation', 'verbose_name_plural': 'Relations'},
        ),
        migrations.RemoveIndex(
            model_name='education',
            name='idx_education_level',
        ),
        migrations.RenameField(
            model_name='insuree',
            old_name='marital',
            new_name='marital_status',
        ),
        migrations.RemoveField(
            model_name='education',
            name='level',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='sort_order',
        ),
    ]
