# Generated by Django 5.2.4 on 2025-08-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0004_alter_education_options_alter_relation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuree',
            old_name='other_health_facility',
            new_name='other_health_facilities',
        ),
    ]
