# Generated by Django 5.2.4 on 2025-08-10 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('insuree', '0005_rename_other_health_facility_insuree_other_health_facilities'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuree',
            name='permission',
        ),
        migrations.AlterField(
            model_name='insuree',
            name='location',
            field=models.ForeignKey(help_text='Location of the insuree', on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.CreateModel(
            name='InsureePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='insuree.insuree')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Insuree Permission',
                'verbose_name_plural': 'Insuree Permissions',
                'db_table': 'tblInsureePermissions',
                'abstract': False,
            },
        ),
    ]
