# Generated by Django 5.2.4 on 2025-08-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0006_remove_insuree_permission_alter_insuree_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsureePermission',
        ),
    ]
