# Generated by Django 5.2.7 on 2025-11-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0007_delete_insureepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(help_text='Identification number', max_length=50)),
                ('identification_type', models.ForeignKey(help_text='Identification type', on_delete=django.db.models.deletion.CASCADE, to='insuree.identificationtype')),
                ('insuree', models.ForeignKey(help_text='Insuree', on_delete=django.db.models.deletion.CASCADE, to='insuree.insuree')),
            ],
            options={
                'verbose_name': 'Insuree Identification',
                'verbose_name_plural': 'Insuree Identifications',
                'db_table': 'tblInsureeIdentifications',
                'managed': True,
            },
        ),
    ]
