# Generated by Django 5.2.7 on 2025-11-04 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0008_insureeidentification'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureeidentification',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the insuree identification', null=True, unique=True),
        ),
    ]
