# Generated by Django 5.2.7 on 2025-11-22 16:43

import uuid

import django.db.models.deletion
from django.db import migrations, models

import modules.claim.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("insurance_coverage", "0004_remove_coverage_legacy_id"),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="claims/attachments/")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the attachment", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Attachment",
                "verbose_name_plural": "Claim Attachments",
                "db_table": "tblClaimAttachments",
            },
        ),
        migrations.CreateModel(
            name="ClaimDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_date",
                    models.DateField(help_text="Date the service was provided"),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        help_text="Code for the service category",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the service or detail",
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount for this claim detail",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Detail",
                "verbose_name_plural": "Claim Details",
                "db_table": "tblClaimDetails",
            },
        ),
        migrations.CreateModel(
            name="ClaimLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity of the item"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price (quantity * unit price)",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Line Item",
                "verbose_name_plural": "Claim Line Items",
                "db_table": "tblClaimLineItems",
            },
        ),
        migrations.CreateModel(
            name="ClaimServiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the service item",
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity of the service item"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total price (quantity * unit price)",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Service Item",
                "verbose_name_plural": "Claim Service Items",
                "db_table": "tblClaimServiceItems",
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=modules.claim.utils.claim_code_generator,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("claim_date", models.DateField()),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency"),
                            ("routine", "Routine"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("group", "Group")],
                        default="individual",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "use",
                    models.CharField(
                        choices=[
                            ("claim", "Claim"),
                            ("preauthorization", "Pre-authorization"),
                            ("predetermination", "Predetermination"),
                        ],
                        default="claim",
                        max_length=30,
                    ),
                ),
                (
                    "coverage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="insurance_coverage.coverage",
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="medical.diagnosis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
                "db_table": "tblClaims",
            },
        ),
    ]
