# Generated by Django 5.2.4 on 2025-08-11 14:01

import django.db.models.deletion
import modules.claim.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_coverage', '0002_initial'),
        ('insuree', '0007_delete_insureepermission'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=modules.claim.utils.claim_code_generator, max_length=50, unique=True)),
                ('claim_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('emergency', 'Emergency'), ('routine', 'Routine'), ('other', 'Other'), ('unknown', 'Unknown'), ('encounter', 'Encounter')], default='unknown', max_length=50)),
                ('claim_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use', models.CharField(choices=[('claim', 'Claim'), ('preauthorization', 'Pre-authorization'), ('predetermination', 'Predetermination')], default='claim', max_length=30)),
                ('coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance_coverage.coverage')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='medical.diagnosis')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insuree.family')),
                ('fourth_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fourth_claims', to='medical.diagnosis')),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='location.healthfacility')),
                ('insuree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insuree.insuree')),
                ('other_diagnosis', models.ManyToManyField(blank=True, related_name='other_claims', to='medical.diagnosis')),
                ('referred_health_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_claims', to='location.healthfacility')),
                ('secondary_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_claims', to='medical.diagnosis')),
                ('third_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_claims', to='medical.diagnosis')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'tblClaims',
            },
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='claims/attachments/')),
                ('description', models.TextField(blank=True, help_text='Description of the attachment', null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='claim.claim')),
            ],
            options={
                'verbose_name': 'Claim Attachment',
                'verbose_name_plural': 'Claim Attachments',
                'db_table': 'tblClaimAttachments',
            },
        ),
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField(help_text='Date the service was provided')),
                ('service_code', models.CharField(blank=True, help_text='Code for the service category', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the service or detail', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount for this claim detail', max_digits=12)),
                ('claim', models.ForeignKey(help_text='The claim this detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='claim.claim')),
            ],
            options={
                'verbose_name': 'Claim Detail',
                'verbose_name_plural': 'Claim Details',
                'db_table': 'tblClaimDetails',
            },
        ),
        migrations.CreateModel(
            name='ClaimLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Description of the item', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the item')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price (quantity * unit price)', max_digits=12)),
                ('claim_detail', models.ForeignKey(help_text='The claim detail this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='claim.claimdetail')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='medical.item')),
            ],
            options={
                'verbose_name': 'Claim Line Item',
                'verbose_name_plural': 'Claim Line Items',
                'db_table': 'tblClaimLineItems',
            },
        ),
        migrations.CreateModel(
            name='ClaimServiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Description of the service item', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the service item')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price (quantity * unit price)', max_digits=12)),
                ('claim_line_item', models.ForeignKey(help_text='The claim line item this service item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='claim.claimlineitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_items', to='medical.service')),
            ],
            options={
                'verbose_name': 'Claim Service Item',
                'verbose_name_plural': 'Claim Service Items',
                'db_table': 'tblClaimServiceItems',
            },
        ),
    ]
