# Generated by Django 5.2.4 on 2025-08-09 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insuree', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('claim_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('emergency', 'Emergency'), ('routine', 'Routine')], max_length=50)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='location.healthfacility')),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insuree.insuree')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'tblClaims',
            },
        ),
    ]
