# Generated by Django 5.2.7 on 2025-11-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claim", "0001_initial"),
        ("insuree", "0001_initial"),
        ("location", "0003_alter_healthfacility_validity_from_and_more"),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="insuree.family",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="fourth_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fourth_claims",
                to="medical.diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="health_facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="location.healthfacility",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="insuree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="insuree.insuree",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="other_diagnosis",
            field=models.ManyToManyField(
                blank=True, related_name="other_claims", to="medical.diagnosis"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="referred_health_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referred_claims",
                to="location.healthfacility",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="secondary_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_claims",
                to="medical.diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="third_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="third_claims",
                to="medical.diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="claimattachment",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="claim.claim",
            ),
        ),
        migrations.AddField(
            model_name="claimdetail",
            name="claim",
            field=models.ForeignKey(
                help_text="The claim this detail belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="claim.claim",
            ),
        ),
        migrations.AddField(
            model_name="claimlineitem",
            name="claim_detail",
            field=models.ForeignKey(
                help_text="The claim detail this line item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="claim.claimdetail",
            ),
        ),
        migrations.AddField(
            model_name="claimlineitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_items",
                to="medical.item",
            ),
        ),
        migrations.AddField(
            model_name="claimserviceitem",
            name="claim_line_item",
            field=models.ForeignKey(
                help_text="The claim line item this service item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_items",
                to="claim.claimlineitem",
            ),
        ),
        migrations.AddField(
            model_name="claimserviceitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_items",
                to="medical.service",
            ),
        ),
    ]
