# Generated by Django 5.2.4 on 2025-08-10 14:08

import django.db.models.deletion
import modules.claim.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
        ('location', '0002_rename_created_at_healthfacility_created_date_and_more'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='fourth_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fourth_claims', to='medical.diagnosis'),
        ),
        migrations.AddField(
            model_name='claim',
            name='other_diagnosis',
            field=models.ManyToManyField(blank=True, related_name='other_claims', to='medical.diagnosis'),
        ),
        migrations.AddField(
            model_name='claim',
            name='referred_health_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_claims', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='claim',
            name='secondary_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_claims', to='medical.diagnosis'),
        ),
        migrations.AddField(
            model_name='claim',
            name='third_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_claims', to='medical.diagnosis'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='code',
            field=models.CharField(default=modules.claim.utils.claim_code_generator, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='medical.diagnosis'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='visit_type',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('routine', 'Routine'), ('other', 'Other'), ('unknown', 'Unknown'), ('encounter', 'Encounter')], default='unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='claim.claim')),
            ],
            options={
                'verbose_name': 'Claim Attachment',
                'verbose_name_plural': 'Claim Attachments',
                'db_table': 'tblClaimAttachments',
            },
        ),
    ]
