# Generated by Django 5.2.4 on 2025-08-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_claimitem_claim_fourth_diagnosis_and_more'),
        ('insuree', '0004_alter_education_options_alter_relation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insuree.family'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='insuree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insuree.insuree'),
        ),
    ]
