# Generated by Django 5.2.4 on 2025-08-11 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_claim_claim_type_claim_family_alter_claim_insuree'),
        ('insurance_coverage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance_coverage.coverage'),
        ),
        migrations.AddField(
            model_name='claim',
            name='use',
            field=models.CharField(choices=[('claim', 'Claim'), ('preauthorization', 'Pre-authorization'), ('predetermination', 'Predetermination')], default='claim', max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
