# Generated by Django 5.2.4 on 2025-08-11 02:16

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('insurance_plan', '0002_remove_insuranceplan_audit_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('policy_holder_id', models.TextField()),
                ('payor_id', models.TextField()),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='insurance_plan.insuranceplan')),
                ('payor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_payor_type', to='contenttypes.contenttype')),
                ('policy_holder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'tblCoverage',
            },
        ),
    ]
