# Generated by Django 5.2.4 on 2025-08-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('insurance_coverage', '0001_initial'),
        ('insurance_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='insurance_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='insurance_plan.insuranceplan'),
        ),
        migrations.AddField(
            model_name='coverage',
            name='payor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_payor_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coverage',
            name='policy_holder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
