# Generated by Django 5.2.4 on 2025-08-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_coverage', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coverage',
            table='tblCoverages',
        ),
    ]
