# Generated by Django 5.2.7 on 2025-11-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_coverage", "0003_alter_coverage_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverage",
            name="legacy_id",
        ),
    ]
