# Generated by Django 5.2.4 on 2025-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('fax', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblOrganization',
            },
        ),
    ]
