# Generated by Django 5.2.4 on 2025-08-10 14:08

import django.db.models.deletion
import django.utils.timezone
import modules.medical.utils
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblMedicalCareTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=modules.medical.utils.generate_medical_code, max_length=6)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblDiagnosis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblMedicalPackages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatientCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblPatientCategories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblServiceCategories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDiagnosis',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(default=modules.medical.utils.generate_medical_code, max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical diagnosis',
                'verbose_name_plural': 'historical diagnosiss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique identifier code', max_length=6)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('entered-in-error', 'Entered in Error'), ('draft', 'Draft')], default='active', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('frequency', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('care_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='medical.caretype')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.itemtype')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='medical.medicalpackage')),
                ('patient_category', models.ForeignKey(default=15, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='medical.patientcategory')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(help_text='Unique identifier code', max_length=6)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('entered-in-error', 'Entered in Error'), ('draft', 'Draft')], default='active', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('frequency', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('care_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.caretype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.itemtype')),
                ('package', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.medicalpackage')),
                ('patient_category', models.ForeignKey(blank=True, db_constraint=False, default=15, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical.patientcategory')),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('packagetype', models.CharField(choices=[('S', 'Single'), ('P', 'Package'), ('C', 'Combination')], default='S', max_length=1)),
                ('manualPrice', models.BooleanField(default=False)),
                ('level', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('care_type', models.CharField(choices=[('S', 'Service'), ('P', 'Procedure'), ('C', 'Consultation')], max_length=1)),
                ('frequency', models.SmallIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='medical.servicecategory')),
            ],
            options={
                'db_table': 'tblServices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceContainedPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_provided', models.IntegerField(blank=True, null=True)),
                ('scp_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('price_asked', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('entered-in-error', 'Entered in Error'), ('draft', 'Draft')], default='active', max_length=20)),
                ('parent', models.ForeignKey(db_column='ServiceLinked', on_delete=django.db.models.deletion.DO_NOTHING, to='medical.service')),
                ('service', models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicesServices', to='medical.service')),
            ],
            options={
                'db_table': 'tblServiceContainedPackages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_provided', models.IntegerField(blank=True, null=True)),
                ('pcp_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('price_asked', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('entered-in-error', 'Entered in Error'), ('draft', 'Draft')], default='active', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.service')),
            ],
            options={
                'db_table': 'tblServiceItems',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['code'], name='medical_ite_code_ef1c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='medical_ite_status_73cc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['care_type'], name='medical_ite_care_ty_9e9d54_idx'),
        ),
    ]
