# Generated by Django 5.2.4 on 2025-08-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_facility',
            field=models.ForeignKey(blank=True, help_text='Health facility of the user', null=True, on_delete=django.db.models.deletion.PROTECT, to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location of the user', null=True, on_delete=django.db.models.deletion.PROTECT, to='location.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_application_type',
            field=models.CharField(choices=[('REGULAR_USER', 'Regular User'), ('LOCATION_BASED_USER', 'Location Based User'), ('HEALTH_FACILITY_USER', 'Health Facility User')], default='REGULAR_USER', help_text='Type of user application', max_length=255),
        ),
    ]
