# Generated by Django 5.2.4 on 2025-08-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_health_facility_user_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_activate_user', 'Can Activate user'), ('can_deactivate_user', 'Can De-Activate user'), ('can_reset_user_password', 'Can Reset User password user'), ('can_view_insurees', 'Can View Insurees')]},
        ),
    ]
