# Generated by Django 5.2.7 on 2025-11-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_application_type',
        ),
    ]
