# Generated by Django 5.2.4 on 2025-08-11 15:03

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionplan',
            name='allows_partial_payment',
            field=models.BooleanField(default=False, help_text='Whether partial payments are allowed'),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='audit_user',
            field=models.ForeignKey(blank=True, help_text='User who last modified the plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Whether contributions auto-renew'),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base contribution amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='calculation_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERC_INC', 'Percentage of Income'), ('PERC_PREM', 'Percentage of Premium'), ('TIERED', 'Tiered by Income'), ('CUSTOM', 'Custom Formula')], default='FIXED', help_text='How contributions are calculated', max_length=10),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='code',
            field=models.CharField(help_text='Unique code for the contribution plan', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='contribution_frequency',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('SA', 'Semi-Annual'), ('A', 'Annual'), ('OT', 'One Time')], default='M', help_text='How often contributions are due', max_length=2),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency for contributions (ISO 4217 code)', max_length=3),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='custom_formula',
            field=models.TextField(blank=True, help_text='Custom formula for contribution calculation (Python expression)', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the plan', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='effective_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the plan becomes effective'),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date when the plan expires', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Grace period in days for late payments'),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Whether participation in this plan is mandatory'),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum age for eligibility', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='max_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum contribution amount', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='max_income_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum income threshold for eligibility', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age for eligibility', null=True),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='min_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum contribution amount', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='min_income_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum income threshold for eligibility', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='name',
            field=models.CharField(help_text='Name of the contribution plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='percentage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage rate for percentage-based calculations', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='plan_type',
            field=models.CharField(choices=[('IND', 'Individual'), ('FAM', 'Family'), ('GRP', 'Group'), ('COM', 'Community')], default='FAM', help_text='Type of contribution plan', max_length=3),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AC', 'Active'), ('SU', 'Suspended'), ('EX', 'Expired'), ('CA', 'Cancelled')], default='DR', help_text='Current status of the plan', max_length=2),
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the contribution plan', unique=True),
        ),
    ]
