# Generated by Django 5.2.4 on 2025-08-11 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution_plan', '0002_alter_contributionplan_allows_partial_payment_and_more'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contributionplan',
            name='chk_contrib_plan_dates',
        ),
        migrations.RemoveIndex(
            model_name='contributionplan',
            name='idx_contrib_plan_effective',
        ),
        migrations.RemoveIndex(
            model_name='contributionplan',
            name='idx_contrib_plan_expiry',
        ),
        migrations.RemoveField(
            model_name='contributionplan',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='contributionplan',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='contributionplan',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AC', 'Active'), ('SU', 'Suspended'), ('EX', 'Expired'), ('CA', 'Cancelled'), ('IN', 'Inactive')], default='DR', help_text='Current status of the plan', max_length=2),
        ),
        migrations.AddIndex(
            model_name='contributionplan',
            index=models.Index(fields=['validity_from'], name='idx_contrib_plan_validity_from'),
        ),
        migrations.AddIndex(
            model_name='contributionplan',
            index=models.Index(fields=['validity_to'], name='idx_contrib_plan_validity_to'),
        ),
        migrations.AddConstraint(
            model_name='contributionplan',
            constraint=models.CheckConstraint(condition=models.Q(('validity_from__lte', models.F('validity_to')), ('validity_to__isnull', True), _connector='OR'), name='chk_contrib_plan_dates'),
        ),
    ]
