# Generated by Django 5.2.4 on 2025-08-11 16:02

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution_plan', '0003_remove_contributionplan_chk_contrib_plan_dates_and_more'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contributionplanbundle',
            name='chk_bundle_dates',
        ),
        migrations.RemoveIndex(
            model_name='contributionplanbundle',
            name='idx_bundle_effective',
        ),
        migrations.RemoveIndex(
            model_name='contributionplanbundle',
            name='idx_bundle_expiry',
        ),
        migrations.RemoveField(
            model_name='contributionplanbundle',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='contributionplanbundle',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='contributionplanbundle',
            name='validity_from',
            field=models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now, help_text='Date when the bundle becomes effective'),
        ),
        migrations.AlterField(
            model_name='contributionplanbundle',
            name='validity_to',
            field=models.DateTimeField(blank=True, db_column='ValidityTo', help_text='Date when the bundle expires', null=True),
        ),
        migrations.AddIndex(
            model_name='contributionplanbundle',
            index=models.Index(fields=['validity_from'], name='idx_bundle_validity_from'),
        ),
        migrations.AddIndex(
            model_name='contributionplanbundle',
            index=models.Index(fields=['validity_to'], name='idx_bundle_validity_to'),
        ),
        migrations.AddConstraint(
            model_name='contributionplanbundle',
            constraint=models.CheckConstraint(condition=models.Q(('validity_from__lte', models.F('validity_to')), ('validity_to__isnull', True), _connector='OR'), name='chk_bundle_dates'),
        ),
    ]
