# Generated by Django 5.2.7 on 2025-11-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contribution_plan",
            "0004_remove_contributionplanbundle_chk_bundle_dates_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributionplan",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="contributionplanbundle",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="contributionplanbundleitem",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="contributionplanbundletier",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="contributiontieredrate",
            name="legacy_id",
        ),
    ]
