# Generated by Django 5.2.4 on 2025-08-09 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contribution_plan', '0001_initial'),
        ('insuree', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='FormalSectorCode', max_length=32)),
                ('trade_name', models.CharField(db_column='TradeName', max_length=255)),
                ('sector_type', models.CharField(max_length=10)),
                ('sector_type_other', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.JSONField(blank=True, db_column='Address', null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=16, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=16, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('contact_name', models.JSONField(blank=True, db_column='ContactName', null=True)),
                ('legal_form', models.IntegerField(blank=True, db_column='LegalForm', null=True)),
                ('activity_code', models.IntegerField(blank=True, db_column='ActivityCode', null=True)),
                ('accountancy_account', models.CharField(blank=True, db_column='AccountancyAccount', max_length=64, null=True)),
                ('bank_account', models.JSONField(blank=True, db_column='bankAccount', null=True)),
                ('payment_reference', models.CharField(blank=True, db_column='PaymentReference', max_length=128, null=True)),
                ('location', models.ForeignKey(blank=True, db_column='LocationsId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
            ],
            options={
                'db_table': 'tblFormalSector',
            },
        ),
        migrations.CreateModel(
            name='FormalSectorInsuree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_plan_bundle', models.ForeignKey(blank=True, db_column='ContributionPlanBundleId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.contributionplanbundle')),
                ('formal_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formal_sector.formalsector')),
                ('insuree', models.ForeignKey(db_column='InsureeId', on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree')),
            ],
            options={
                'db_table': 'tblFormalSectorInsuree',
            },
        ),
        migrations.CreateModel(
            name='FormalSectorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_sector', models.ForeignKey(db_column='PolicyHolderId', on_delete=django.db.models.deletion.DO_NOTHING, to='formal_sector.formalsector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblFormalSectorUsers',
            },
        ),
    ]
