# Generated by Django 5.2.7 on 2025-11-22 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contribution_plan", "0005_remove_contributionplan_legacy_id_and_more"),
        ("location", "0003_alter_healthfacility_validity_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormalSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("trade_name", models.CharField(max_length=255)),
                (
                    "sector_type",
                    models.CharField(
                        choices=[
                            ("PRS", "Private Sector"),
                            ("PUS", "Public Sector"),
                            ("NS", "NGO Sector"),
                            ("IS", "International Sector"),
                            ("CS", "Cooperative Sector"),
                            ("AS", "Association Sector"),
                            ("SE", "Self Employed Sector"),
                            ("INS", "Informal Sector"),
                            ("FS", "Formal Sector"),
                            ("OS", "Other Sectors"),
                        ],
                        default="PRS",
                        max_length=10,
                    ),
                ),
                (
                    "sector_type_other",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=16, null=True)),
                ("fax", models.CharField(blank=True, max_length=16, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_name", models.JSONField(blank=True, null=True)),
                ("legal_form", models.IntegerField(blank=True, null=True)),
                ("activity_code", models.IntegerField(blank=True, null=True)),
                (
                    "accountancy_account",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("bank_account", models.JSONField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="location.location",
                    ),
                ),
            ],
            options={
                "db_table": "tblFormalSector",
            },
        ),
        migrations.CreateModel(
            name="FormalSectorInsuree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the formal sector insuree",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "contribution_plan_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="contribution_plan.contributionplanbundle",
                    ),
                ),
                (
                    "formal_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formal_sector.formalsector",
                    ),
                ),
            ],
            options={
                "db_table": "tblFormalSectorInsuree",
            },
        ),
    ]
