# Generated by Django 5.2.7 on 2025-11-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formal_sector", "0001_initial"),
        ("insuree", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formalsectorinsuree",
            name="insuree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="insuree.insuree"
            ),
        ),
    ]
