# Generated by Django 5.2.4 on 2025-08-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution_plan', '0002_alter_contributionplan_allows_partial_payment_and_more'),
        ('formal_sector', '0002_delete_formalsectoruser'),
        ('insuree', '0007_delete_insureepermission'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalsector',
            name='accountancy_account',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='activity_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='bank_account',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='contact_name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='fax',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='legal_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='formalsector',
            name='trade_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formalsectorinsuree',
            name='contribution_plan_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.contributionplanbundle'),
        ),
        migrations.AlterField(
            model_name='formalsectorinsuree',
            name='insuree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
    ]
