# Generated by Django 5.2.4 on 2025-08-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formal_sector', '0003_alter_formalsector_accountancy_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalsector',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
