# Generated by Django 5.2.7 on 2025-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formal_sector', '0004_alter_formalsector_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalsector',
            name='sector_type',
            field=models.CharField(choices=[('PRS', 'Private Sector'), ('PUS', 'Public Sector'), ('NS', 'NGO Sector'), ('IS', 'International Sector'), ('CS', 'Cooperative Sector'), ('AS', 'Association Sector'), ('SE', 'Self Employed Sector'), ('INS', 'Informal Sector'), ('FS', 'Formal Sector'), ('OS', 'Other Sectors')], default='PRS', max_length=10),
        ),
    ]
