# Generated by Django 5.2.7 on 2025-11-04 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formal_sector', '0005_alter_formalsector_sector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsectorinsuree',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the formal sector insuree', null=True, unique=True),
        ),
    ]
