# Generated by Django 5.2.1 on 2025-05-13 12:56

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Location Type Name')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Hierarchy Level')),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'db_table': 'tblLocationTypes',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Location Name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='location.location', verbose_name='Parent Location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.locationtype', verbose_name='Location Type')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'tblLocations',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Facility Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Facility Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Facility Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.location', verbose_name='Facility Location')),
            ],
            options={
                'verbose_name': 'Health Facility',
                'verbose_name_plural': 'Health Facilities',
                'db_table': 'tblHealthFacilities',
                'ordering': ['name'],
            },
        ),
    ]
