# Generated by Django 5.2.4 on 2025-08-10 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_created_at_healthfacility_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='validity_from',
            field=models.DateTimeField(db_column='ValidityFrom', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalhealthfacility',
            name='validity_from',
            field=models.DateTimeField(db_column='ValidityFrom', default=django.utils.timezone.now),
        ),
    ]
