# Generated by Django 5.2.4 on 2025-08-11 15:03

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_plan', '0001_initial'),
        ('location', '0003_alter_healthfacility_validity_from_and_more'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='enroll_date',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='offline',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='updation_date',
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='code',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='plan_scope_type',
            field=models.CharField(blank=True, choices=[('L', 'Location Based'), ('M', 'Member Based'), ('P', 'Product Based'), ('S', 'Service Based'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='recurrence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='InsurancePlanItem',
            fields=[
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_plan.insuranceplan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.item')),
            ],
            options={
                'db_table': 'tblInsurancePlanItems',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsurancePlanService',
            fields=[
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_plan.insuranceplan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.service')),
            ],
            options={
                'db_table': 'tblInsurancePlanServices',
                'managed': True,
            },
        ),
    ]
