# Generated by Django 5.2.4 on 2025-08-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='audit_user_id',
        ),
    ]
