# Generated by Django 5.2.7 on 2025-11-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_plan", "0002_remove_insuranceplan_creation_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insuranceplan",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="insuranceplanitem",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="insuranceplanservice",
            name="legacy_id",
        ),
    ]
